name: Build and Push to Self-Hosted Docker Registry

on:
  push:
    branches: ["main"]
    paths:
      - '**'

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  deploy-kubectl:
    runs-on: "self-hosted" 
    steps:
      - name: Rollout restart
        uses: actions-hub/kubectl@v1.31.1
        with:
          args: rollout restart deployment website -n website
